### ISSUE TITLE
Inference

### ISSUE THREAD

**Issue by daniel-richter** [fabiozappo/SkeletonGroupActivityRecognition#5]
How can I use your solution for inference - put the model into action on live data (resp. single images) to produce actionable output?

**Comment by fabiozappo** [comment]
Inference on images is no implemented, however the pipeline should be something similar to this:

- run openpose on the image
- find the actors (volleyball players) and stack them in a single tensor
- perform the same preprocessing used in dataset.py
- feed the whole tensor into the network

Let me know if you have any other question about it!
